---
ignored:
  - DL3006 # We do specify our tags as a variable, hadolint doesn't detect this
  - DL3013 # We want the latest pip packages
  - DL3033 # We want the latest packages unless we have pinned them
  - DL4006 # Disable pipefail as we are using bash not sh
failure-threshold: warning
...
