version: 0.2

phases:
  install:
    commands:
      - /bin/sh ./scripts/codebuild-install.sh

  build:
    commands:
      - /bin/sh ./scripts/codebuild-build.sh
      - aws s3 cp ./incoming-message-handler/build/ s3://$S3_BUCKET/audit-logging/ --exclude "*.txt"
      - aws s3 cp ./incoming-message-handler/environment/infrastructure/state-machine.json s3://$S3_BUCKET/audit-logging/state-machine.json

artifacts:
  files:
    - incoming-message-handler/build/*.js
