---

version: 0.2

phases:
  install:
    commands:
      - yum install -y zip
      - amazon-linux-extras install docker -y
      - dockerd &> dockerd-logfile &
  build:
    commands:
      - scripts/install-all.sh
      - make build
      - scripts/codebuild-artifacts.sh
...
