version: 0.2

phases:
  install:
    commands:
      - /bin/bash ./scripts/codebuild-install.sh

  build:
    commands:
      - /bin/bash ./scripts/install-all.sh
      - /bin/bash ./scripts/build-all.sh
      - /bin/bash ./scripts/codebuild-artifacts.sh
