---
version: 0.2

phases:
  install:
    commands:
      - yum install -y jq
      - yum install which -y
      - yum install postgresql-devel -y
      - yum install gcc-c++ -y
      - dockerd &> dockerd-logfile &
  build:
    commands:
      - npm install
      - npm run build
      - scripts/upload-codebuild-artifacts.sh
