version: 0.2

phases:
  install:
    commands:
      - /bin/sh ./scripts/codebuild-install.sh

  build:
    commands:
      - /bin/sh ./scripts/codebuild-build.sh

artifacts:
  files:
    - incoming-message-handler/build/*
