version: 0.2

phases:
  install:
    commands:
      - /bin/sh ./scripts/codebuild-install.sh

  build:
    commands:
      - /bin/sh ./scripts/codebuild-build.sh
      - touch test.txt

artifacts:
  files:
    - test.txt
    - incoming-message-handler/build/formatMessage.js
    - incoming-message-handler/build/logMessageReceipt.js
    - incoming-message-handler/build/parseMessage.js
    - incoming-message-handler/build/retrieveFromS3.js
    - incoming-message-handler/build/sendToBichard.js
