version: 0.2

phases:
  install:
    commands:
      - /bin/sh ./scripts/codebuild-install.sh

  build:
    commands:
      - /bin/sh ./scripts/codebuild-build.sh
      - echo $S3_BUCKET
      - aws s3 sync incoming-message-handler/build/ s3://$S3_BUCKET/audit-logging --acl bucket-owner-full-control

artifacts:
  files:
    - incoming-message-handler/build/*.js
