---

version: 0.2


env:
  exported-variables:
    - AUDIT_LOGGING_HASH

phases:
  install:
    commands:
      - yum install -y zip
      - amazon-linux-extras install docker -y
      - dockerd &> dockerd-logfile &
  build:
    commands:
      - scripts/install-all.sh
      - scripts/build-all.sh
      - . scripts/codebuild-artifacts.sh
...
