---

version: 0.2

phases:
  install:
    commands:
      - yum install -y zip
      - amazon-linux-extras install docker
  build:
    commands:
      - scripts/install-all.sh
      - scripts/build-all.sh
      - scripts/codebuild-artifacts.sh
...
