service: audit-log-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 200
  environment:
    AWS_URL: http://localhost:8000
    DYNAMO_REGION: eu-west-2
    AUDIT_LOG_TABLE_NAME: auditLogTable
    AUDIT_LOG_EVENTS_TABLE_NAME: auditLogEventsTable
    MQ_USER: admin
    MQ_PASSWORD: admin
    MQ_URL: failover:(stomp://localhost:51613)
    INTERNAL_INCOMING_MESSAGES_BUCKET: internalIncomingBucket
    AUDIT_LOG_EVENTS_BUCKET: auditLogEventsBucket
    S3_URL: http://localhost:4569
    S3_REGION: eu-west-2
    API_URL: http://localhost:3010
    API_KEY: dummy
    S3_AWS_ACCESS_KEY_ID: S3RVER
    S3_AWS_SECRET_ACCESS_KEY: S3RVER
    DYNAMO_AWS_ACCESS_KEY_ID: S3RVER
    DYNAMO_AWS_SECRET_ACCESS_KEY: S3RVER
    DB_HOST: "localhost"
    DB_PORT: "5433"
    DB_USER: "bichard"
    DB_PASSWORD: "password"
    DB_TABLE_NAME: "archive_error_list"
    DB_SSL: "false"
    DB_NAME: "bichard"
    DB_SCHEMA: "br7own"

plugins:
  - serverless-offline
  - serverless-hooks
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-s3-local

custom:
  serverless-offline:
    host: 0.0.0.0
  esbuild:
    bundle: true
    minify: false
    external:
      - pg-native
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  s3:
    host: 0.0.0.0
    directory: /tmp
  serverless-hooks:
    hookPrefix: hook
    runAllOptions:
      stderr: true
      stdout: true
      stdin: true

resources:
  Resources:
    auditLogEventsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: auditLogEventsBucket
    externalIncomingBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: externalIncomingBucket
    internalIncomingBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: internalIncomingBucket
    conductorIncomingBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: conductorIncomingBucket
    auditLogEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: auditLogEventsTable
        AttributeDefinitions:
          - AttributeName: _
            AttributeType: S
          - AttributeName: _id
            AttributeType: S
          - AttributeName: _messageId
            AttributeType: S
          - AttributeName: user
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
          - AttributeName: _automationReport
            AttributeType: N
          - AttributeName: _topExceptionsReport
            AttributeType: N
          - AttributeName: eventCode
            AttributeType: S
          - AttributeName: category
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: timestampIndex
            KeySchema:
              - AttributeName: _
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: messageIdIndex
            KeySchema:
              - AttributeName: _messageId
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: userIndex
            KeySchema:
              - AttributeName: user
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: eventCodeIndex
            KeySchema:
              - AttributeName: eventCode
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: categoryIndex
            KeySchema:
              - AttributeName: category
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: automationReportIndex
            KeySchema:
              - AttributeName: _messageId
                KeyType: HASH
              - AttributeName: _automationReport
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: topExceptionsReportIndex
            KeySchema:
              - AttributeName: _messageId
                KeyType: HASH
              - AttributeName: _topExceptionsReport
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    auditLogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: auditLogTable
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: S
          - AttributeName: _
            AttributeType: S
          - AttributeName: receivedDate
            AttributeType: S
          - AttributeName: externalCorrelationId
            AttributeType: S
          - AttributeName: messageHash
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: caseId
            AttributeType: S
          - AttributeName: isSanitised
            AttributeType: N
          - AttributeName: nextSanitiseCheck
            AttributeType: S
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: receivedDateIndex
            KeySchema:
              - AttributeName: _
                KeyType: HASH
              - AttributeName: receivedDate
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: externalCorrelationIdIndex
            KeySchema:
              - AttributeName: externalCorrelationId
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: messageHashIndex
            KeySchema:
              - AttributeName: messageHash
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: statusIndex
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: receivedDate
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: caseIdIndex
            KeySchema:
              - AttributeName: caseId
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: isSanitisedIndex
            KeySchema:
              - AttributeName: isSanitised
                KeyType: HASH
              - AttributeName: nextSanitiseCheck
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  getMessages:
    handler: src/audit-log-api/handlers/getMessages.default
    events:
      - httpApi:
          path: /messages
          method: get
  getMessage:
    handler: src/audit-log-api/handlers/getMessages.default
    events:
      - httpApi:
          path: /messages/{messageId}
          method: get
  createAuditLog:
    handler: src/audit-log-api/handlers/createAuditLog.default
    events:
      - httpApi:
          path: /messages
          method: post
  createAuditLogEvents:
    handler: src/audit-log-api/handlers/createAuditLogEvents.default
    events:
      - httpApi:
          path: /messages/{messageId}/events
          method: post
  retryMessage:
    handler: src/audit-log-api/handlers/retryMessage.default
    events:
      - httpApi:
          path: /messages/{messageId}/retry
          method: post
  sanitiseMessage:
    handler: src/audit-log-api/handlers/sanitiseMessage.default
    events:
      - httpApi:
          path: /messages/{messageId}/sanitise
          method: post
  createAuditLogUserEvents:
    handler: src/audit-log-api/handlers/createAuditLogUserEvents.default
    events:
      - httpApi:
          path: /users/{userName}/events
          method: post
