version: "3.2"
services:
  ibmmq:
    image: ibmcom/mq
    container_name: ibmmq
    ports:
      - 1414:1414
      - 10443:9443
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=BR7_QM

  localstack:
    image: localstack/localstack
    container_name: localstack_main
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs,lambda,s3,dynamodb,stepfunctions,apigateway
      - DEBUG=1
      - LAMBDA_REMOTE_DOCKER=false
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - LAMBDA_DOCKER_NETWORK=bichard_audit_logging
      - LAMNDA_REMOVE_CONTAINERS=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: bichard_audit_logging
    driver: bridge
