version: "3.2"
services:
  mq:
    image: rmohr/activemq
    ports:
      - 58161:8161
      - 51613:61613
    volumes:
      - ./activemq.xml:/opt/activemq/conf/activemq.xml

  localstack:
    image: localstack/localstack
    container_name: localstack_main
    ports:
      - 4566:4566
    environment:
      - SERVICES=lambda,s3,dynamodb,stepfunctions,apigateway
      - DEBUG=1
      - LAMBDA_REMOTE_DOCKER=false
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - LAMBDA_DOCKER_NETWORK=bichard_audit_logging
      - LAMNDA_REMOVE_CONTAINERS=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: bichard_audit_logging
    driver: bridge
