version: "3.2"
services:
  mq:
    image: rmohr/activemq
    ports:
      - 58161:8161
      - 51613:61613
    volumes:
      - ./activemq.xml:/opt/activemq/conf/activemq.xml
  pg:
    build:
      context: .
      dockerfile: PgDockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bichard
      POSTGRES_USER: bichard
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    command: postgres -c max_prepared_transactions=100 -c log_statement=all
