version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.9.0
    working_directory: ~
    steps:
      - checkout

      # Load dependencies from the cache if they exist and haven't changed
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-{{ checksum "shared/package-lock.json" }}
            - v1-npm-deps-{{ checksum "incoming-message-handler/package-lock.json" }}
            - v1-npm-deps-{{ checksum "audit-log-api/package-lock.json" }}
            - v1-npm-deps-{{ checksum "audit-log-portal/package-lock.json" }}
      - run: ./scripts/install-all.sh
      - run: ./scripts/build-all.sh
      - run: npm run lint

      # Update the cache with the latest installed dependencies to speed up future installs
      - save_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-{{ checksum "shared/package-lock.json" }}
            - v1-npm-deps-{{ checksum "incoming-message-handler/package-lock.json" }}
            - v1-npm-deps-{{ checksum "audit-log-api/package-lock.json" }}
            - v1-npm-deps-{{ checksum "audit-log-portal/package-lock.json" }}

  test:
    docker:
      - image: cimg/node:15.9.0
    working_directory: ~
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-{{ checksum "shared/package-lock.json" }}
            - v1-npm-deps-{{ checksum "incoming-message-handler/package-lock.json" }}
            - v1-npm-deps-{{ checksum "audit-log-api/package-lock.json" }}
            - v1-npm-deps-{{ checksum "audit-log-portal/package-lock.json" }}
      - run: ./scripts/install-all.sh
      - run: ./scripts/build-all.sh dev
      - run: ./scripts/test-all.sh
      - store_test_results:
          path: ./shared/test-results/jest/
      - store_test_results:
          path: ./incoming-message-handler/test-results/jest/
      - store_test_results:
          path: ./audit-log-api/test-results/jest/
      - store_test_results:
          path: ./audit-log-portal/test-results/jest/

workflows:
  version: 2
  jobs:
    - build
    - test:
        requires:
          - build
