version: 2.1

commands:
    restore_all_caches:
        description: Restore all of the node_modules directories
        steps:
            - run:
                name: Hash package locks
                command: bash ./scripts/hash-package-locks.sh
            - restore_cache:
                key: v1-npm-deps-{{ checksum "package-lock.json.md5" }}
            - restore_cache:
                key: v1-npm-deps-{{ checksum "src/shared/package-lock.json.md5" }}
            - restore_cache:
                key: v1-npm-deps-{{ checksum "src/shared-types/package-lock.json.md5" }}
            - restore_cache:
                key: v1-npm-deps-{{ checksum "src/shared-testing/package-lock.json.md5" }}
            - restore_cache:
                key: v1-npm-deps-{{ checksum "src/lambdas/retrieve-event-from-s3/package-lock.json.md5" }}
            - restore_cache:
                key: v1-npm-deps-{{ checksum "src/lambdas/translate-event/package-lock.json.md5" }}
            - restore_cache:
                key: v1-npm-deps-{{ checksum "src/lambdas/record-event/package-lock.json.md5" }}
            - restore_cache:
                key: v1-npm-deps-{{ checksum "src/message-receiver/package-lock.json.md5" }}
            - restore_cache:
                key: v1-npm-deps-{{ checksum "src/transfer-messages/package-lock.json.md5" }}
            - restore_cache:
                key: v1-npm-deps-{{ checksum "src/event-handler/package-lock.json.md5" }}
            - restore_cache:
                key: v1-npm-deps-{{ checksum "src/incoming-message-handler/package-lock.json.md5" }}
            - restore_cache:
                key: v1-npm-deps-{{ checksum "src/audit-log-api/package-lock.json.md5" }}
            - restore_cache:
                key: v1-npm-deps-{{ checksum "src/audit-log-portal/package-lock.json.md5" }}

    save_all_caches:
        description: Save all of the node_modules directories
        steps:
            - save_cache:
                key: v1-npm-deps-{{ checksum "package-lock.json.md5" }}
                paths: node_modules
            - save_cache:
                key: v1-npm-deps-{{ checksum "src/shared/package-lock.json.md5" }}
                paths: src/shared/node_modules
            - save_cache:
                key: v1-npm-deps-{{ checksum "src/shared-types/package-lock.json.md5" }}
                paths: src/shared-types/node_modules
            - save_cache:
                key: v1-npm-deps-{{ checksum "src/shared-testing/package-lock.json.md5" }}
                paths: src/shared-testing/node_modules
            - save_cache:
                key: v1-npm-deps-{{ checksum "src/lambdas/retrieve-event-from-s3/package-lock.json.md5" }}
                paths: src/lambdas/retrieve-event-from-s3/node_modules
            - save_cache:
                key: v1-npm-deps-{{ checksum "src/lambdas/translate-event/package-lock.json.md5" }}
                paths: src/lambdas/translate-event/node_modules
            - save_cache:
                key: v1-npm-deps-{{ checksum "src/lambdas/record-event/package-lock.json.md5" }}
                paths: src/lambdas/record-event/node_modules
            - save_cache:
                key: v1-npm-deps-{{ checksum "src/message-receiver/package-lock.json.md5" }}
                paths: src/message-receiver/node_modules
            - save_cache:
                key: v1-npm-deps-{{ checksum "src/transfer-messages/package-lock.json.md5" }}
                paths: src/transfer-messages/node_modules
            - save_cache:
                key: v1-npm-deps-{{ checksum "src/event-handler/package-lock.json.md5" }}
                paths: src/event-handler/node_modules
            - save_cache:
                key: v1-npm-deps-{{ checksum "src/incoming-message-handler/package-lock.json.md5" }}
                paths: src/incoming-message-handler/node_modules
            - save_cache:
                key: v1-npm-deps-{{ checksum "src/audit-log-api/package-lock.json.md5" }}
                paths: src/audit-log-api/node_modules
            - save_cache:
                key: v1-npm-deps-{{ checksum "src/audit-log-portal/package-lock.json.md5" }}
                paths: src/audit-log-portal/node_modules

    persist_build_dirs:
        description: Save all of the build directories
        steps:
            - persist_to_workspace:
                root: .
                paths:
                    - src/*/build

    store_results:
        description: "Store the test output"
        steps:
            - store_test_results:
                path: ./src/shared-types/test-results/jest/
            - store_test_results:
                path: ./src/shared/test-results/jest/
            - store_test_results:
                path: ./src/shared-testing/test-results/jest/
            - store_test_results:
                path: ./src/lambdas/retrieve-event-from-s3/test-results/jest/
            - store_test_results:
                path: ./src/lambdas/translate-event/test-results/jest/
            - store_test_results:
                path: ./src/lambdas/record-event/test-results/jest/
            - store_test_results:
                path: ./src/message-receiver/test-results/jest/
            - store_test_results:
                path: ./src/transfer-messages/test-results/jest/
            - store_test_results:
                path: ./src/event-handler/test-results/jest/
            - store_test_results:
                path: ./src/incoming-message-handler/test-results/jest/
            - store_test_results:
                path: ./src/audit-log-api/test-results/jest/
            - store_test_results:
                path: ./src/audit-log-portal/test-results/jest/

jobs:
  build:
    docker:
      - image: cimg/node:16.13.1
    working_directory: ~
    steps:
      - checkout
      - restore_all_caches
      - run: make install
      - run: make validate
      - run: make build-all
      - run:
          name: Build Portal Stories
          command: cd src/audit-log-portal && npm run build-storybook && cd -
      - save_all_caches
      - persist_build_dirs

  test:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    resource_class: large
    working_directory: ~
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_all_caches
      - run:
          name: Install Nodejs version in .nvmrc
          command: nvm install
      - run:
          name: Install all
          command: nvm use && ./scripts/install-all.sh
      - run:
          name: Install Java
          command: sudo apt-get update && sudo apt-get install openjdk-17-jre
      - run:
          name: Install Dynamo
          command: make -C ./src/audit-log-api install-dynamo
      - run:
          name: Start Audit Log API
          command: nvm use && make run-api
          background: true
      - run:
          name: Wait for Audit Log API
          command: cd src/audit-log-api && npm run wait-for-api
      - run:
          name: Running unit, integration, and end-to-end tests
          command: nvm use && make test
      - store_results


  cypress-test:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    resource_class: large
    working_directory: ~
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_all_caches
      - run:
          name: Install Nodejs version in .nvmrc
          command: nvm install
      - run:
          name: Install all
          command: nvm use && ./scripts/install-all.sh
      - run:
          name: Install Cypress
          command: ./.circleci/scripts/install-cypress.sh
      - run:
          name: Run UI tests
          command: cd ./src/audit-log-portal && npm run test:ui
      - store_artifacts:
          path: ./src/audit-log-portal/cypress/videos
      - store_artifacts:
          path: ./src/audit-log-portal/cypress/screenshots

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - cypress-test:
          requires:
            - build
