version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:15.9.0
    working_directory: ~
    steps:
      - checkout
      - run:
          name: Install root dependencies
          command: npm i
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  check_deps:
    docker:
      - image: cimg/node:15.9.0
    working_directory: ~
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check workspace dependencies
          command: ls

  build:
    docker:
      - image: cimg/node:15.9.0
    working_directory: ~
    steps:
      - checkout
      - run:
          name: Install root dependencies
          command: npm i
      - run:
          name: Install the dependencies for the Handlers Common module
          command: cd ./shared && npm i
      - run:
          name: Build the Handlers Common module
          command: cd ./shared && npm run build
      - run:
          name: Install the dependencies for the Incoming Message Handler project
          command: cd ./incoming-message-handler && npm i
      - run:
          name: Build the Incoming Message Handler project
          command: cd ./incoming-message-handler && npm run build
      - run:
          name: Install the dependencies for the Audit Log API project
          command: cd ./audit-log-api && npm i
      - run:
          name: Build the Audit Log API project
          command: cd ./audit-log-api && npm run build
      - run:
          name: Install the dependencies for the Audit Log Portal project
          command: cd ./audit-log-portal && npm i
      - run:
          name: Build the Audit Log Portal project
          command: cd ./audit-log-portal && npm run build
      - run:
          name: Run lint
          command: npm run lint

  test:
    docker:
      - image: cimg/node:15.9.0
    working_directory: ~
    steps:
      - checkout
      - run:
          name: Install the dependencies for the Shared library
          command: cd ./shared && npm i
      - run:
          name: Build the Shared library
          command: cd ./shared && npm run build
      - run:
          name: Run all unit tests for the Shared library
          command: cd ./shared && npm run test:ci
      - store_test_results:
          path: ./shared/test-results/jest/
      - run:
          name: Install the dependencies for the Incoming Message Handler project
          command: cd ./incoming-message-handler && npm i
      - run:
          name: Build the Incoming Message Handler project
          command: cd ./incoming-message-handler && npm run build
      - run:
          name: Run all unit tests for the Incoming Message Handler project
          command: cd ./incoming-message-handler && npm run test:ci
      - store_test_results:
          path: ./incoming-message-handler/test-results/jest/
      - run:
          name: Install the dependencies for the Audit Log API project
          command: cd ./audit-log-api && npm i
      - run:
          name: Build the Audit Log API project
          command: cd ./audit-log-api && npm run build
      - run:
          name: Run all unit tests for the Audit Log API project
          command: cd ./audit-log-api && npm run test:ci
      - store_test_results:
          path: ./audit-log-api/test-results/jest/
      - run:
          name: Install the dependencies for the Audit Log Portal project
          command: cd ./audit-log-portal && npm i
      - run:
          name: Build the Audit Log Portal project
          command: cd ./audit-log-portal && npm run build
      - run:
          name: Run all unit tests for the Audit Log Portal project
          command: cd ./audit-log-portal && npm run test:ci
      - store_test_results:
          path: ./audit-log-portal/test-results/jest/

workflows:
  version: 2
  prototyping:
    jobs:
      - install_dependencies
      - check_deps:
          requires:
            - install_dependencies

  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
