version: 2.1

jobs:
  install:
    docker:
      - image: cimg/node:15.9.0
    working_directory: ~
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: ./scripts/install-all.sh
      - persist_to_workspace:
          root: .
          paths:
            - ./**

  build:
    docker:
      - image: cimg/node:15.9.0
    working_directory: ~
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ls incoming-message-handler
      - run:
          name: Build all projects
          command: ./scripts/build-all.sh
      - run:
          name: Run lint
          command: npm run lint

  test:
    docker:
      - image: cimg/node:15.9.0
    working_directory: ~
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run all tests
          command: ./scripts/test-all.sh
      - store_test_results:
          path: ./shared/test-results/jest/
      - store_test_results:
          path: ./incoming-message-handler/test-results/jest/
      - store_test_results:
          path: ./audit-log-api/test-results/jest/
      - store_test_results:
          path: ./audit-log-portal/test-results/jest/

workflows:
  version: 2
  build-and-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
