---

version: 2.1

commands:
    restore_all_caches:
        description: Restore all of the node_modules directories
        steps:
            - run:
                name: Hash package locks
                command: bash ./scripts/hash-package-locks.sh
            - restore_cache:
                key: v1-npm-deps-{{ checksum "package-lock.json.md5" }}

    save_all_caches:
        description: Save all of the node_modules directories
        steps:
            - save_cache:
                key: v1-npm-deps-{{ checksum "package-lock.json.md5" }}
                paths: node_modules

    persist_build_dirs:
        description: Save all of the build directories
        steps:
            - persist_to_workspace:
                root: .
                paths:
                    - build

    store_results:
        description: "Store the test output"
        steps:
            - store_test_results:
                path: ./test-results/jest/

jobs:
  build:
    docker:
      - image: cimg/node:16.13.1
    resource_class: xlarge
    working_directory: ~
    steps:
      - checkout
      - restore_all_caches
      - run: npm install
      - save_all_caches
      - run: npm run check
      - run: npm run lint
      - run: npm run build
      - persist_build_dirs

  build-test-lambdas:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    resource_class: xlarge
    working_directory: ~
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_all_caches
      - run:
          name: Install Nodejs version in .nvmrc
          command: nvm install
      - run:
          name: Install all
          command: nvm use && npm install
      - run:
          name: Install Java
          command: sudo apt-get update && sudo apt-get install openjdk-17-jre
      - run:
          name: Install Dynamo
          command: npm run install-dynamo
      - run:
          name: Start Audit Log API
          command: nvm use && npm run start-api
          background: true
      - run:
          name: Wait for Audit Log API
          command: npm run wait-for-api
      - run:
          name: Running unit tests
          command: nvm use && npm run test:unit
      - run:
          name: Running integration tests
          command: nvm use && npm run test:integration
      - run:
          name: Running end-to-end tests
          command: nvm use && npm run test:e2e
      - store_results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - build-test-lambdas
