version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.9.0
    working_directory: ~
    steps:
      - checkout

      # Load dependencies from the cache if they exist and haven't changed
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-{{ checksum "shared/package-lock.json" }}
            - v1-npm-deps-{{ checksum "src/@bichard/testing/package-lock.json" }}
            - v1-npm-deps-{{ checksum "src/@lambdas/store-in-s3/package-lock.json" }}
            - v1-npm-deps-{{ checksum "src/@lambdas/translate-event/package-lock.json" }}
            - v1-npm-deps-{{ checksum "src/@lambdas/record-event/package-lock.json" }}
            - v1-npm-deps-{{ checksum "src/event-handler/package-lock.json" }}
            - v1-npm-deps-{{ checksum "incoming-message-handler/package-lock.json" }}
            - v1-npm-deps-{{ checksum "audit-log-api/package-lock.json" }}
            - v1-npm-deps-{{ checksum "audit-log-portal/package-lock.json" }}
            - v1-npm-deps-{{ checksum "general-event-handler/package-lock.json" }}
            - v1-npm-deps-{{ checksum "mq-listener/package-lock.json" }}

      - run: make build

      - run:
          name: Build Portal Stories
          command: cd audit-log-portal && npm run build-storybook && cd -

      - run: make validate

      # Update the cache with the latest installed dependencies to speed up future installs
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths: node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "shared/package-lock.json" }}
          paths: shared/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "shared/package-lock.json" }}
          paths: src/@bichard/testing/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "shared/package-lock.json" }}
          paths: src/lambdas/store-in-s3/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "shared/package-lock.json" }}
          paths: src/lambdas/translate-event/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "shared/package-lock.json" }}
          paths: src/lambdas/record-event/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "shared/package-lock.json" }}
          paths: src/event-handler/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "incoming-message-handler/package-lock.json" }}
          paths: incoming-message-handler/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "audit-log-api/package-lock.json" }}
          paths: audit-log-api/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "audit-log-portal/package-lock.json" }}
          paths: audit-log-portal/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "general-event-handler/package-lock.json" }}
          paths: general-event-handler/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "mq-listener/package-lock.json" }}
          paths: mq-listener/node_modules

      # Persist all dist/build folders to the workspace to reduce build time later
      - persist_to_workspace:
          root: .
          paths:
            - shared/dist
            - src/@bichard/testing/dist
            - src/lambdas/store-in-s3/build
            - src/lambdas/translate-event/build
            - src/lambdas/record-event/build
            - src/event-handler/build
            - incoming-message-handler/build
            - audit-log-api/build
            - audit-log-portal/.next
            - general-event-handler/build

  test:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    working_directory: ~
    steps:
      - checkout

      # Restore any cached dependencies for the projects to reduce install time
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "shared/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "src/@bichard/testing/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "src/lambdas/store-in-s3/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "src/lambdas/translate-event/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "src/lambdas/record-event/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "src/event-handler/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "incoming-message-handler/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "audit-log-api/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "audit-log-portal/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "general-event-handler/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "mq-listener/package-lock.json" }}

      - run:
          name: Installing Nodejs version in .nvmrc
          command: nvm install

      - run:
          name: Installing and configuring awslocal
          command: ./.circleci/scripts/install-awslocal.sh

      - run:
          name: Installing all
          command: ./scripts/install-all.sh

      # Attach the workspace to retrieve the dist/build folders so we don't have to rebuild
      - attach_workspace:
          at: .

      - run:
          name: Running unit, integration, and end-to-end tests
          command: make test

      - store_test_results:
          path: ./shared/test-results/jest/
      - store_test_results:
          path: ./src/@bichard/testing/test-results/jest/
      - store_test_results:
          path: ./src/lambdas/store-in-s3/test-results/jest/
      - store_test_results:
          path: ./src/lambdas/translate-event/test-results/jest/
      - store_test_results:
          path: ./src/lambdas/record-event/test-results/jest/
      - store_test_results:
          path: ./src/event-handler/test-results/jest/
      - store_test_results:
          path: ./incoming-message-handler/test-results/jest/
      - store_test_results:
          path: ./audit-log-api/test-results/jest/
      - store_test_results:
          path: ./audit-log-portal/test-results/jest/
      - store_test_results:
          path: ./general-event-handler/test-results/jest/

      - run:
          name: Installing Cypress
          command: ./.circleci/scripts/install-cypress.sh

      - run:
          name: Running UI tests
          command: cd ./audit-log-portal && npm run test:ui && cd -

      - store_artifacts:
          path: ./audit-log-portal/cypress/videos
      - store_artifacts:
          path: ./audit-log-portal/cypress/screenshots

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
