version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.9.0
    working_directory: ~
    steps:
      - checkout

      # Load dependencies from the cache if they exist and haven't changed
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-{{ checksum "shared/package-lock.json" }}
            - v1-npm-deps-{{ checksum "incoming-message-handler/package-lock.json" }}
            - v1-npm-deps-{{ checksum "audit-log-api/package-lock.json" }}
            - v1-npm-deps-{{ checksum "audit-log-portal/package-lock.json" }}
      - run: ./scripts/install-all.sh
      - run: ./scripts/build-all.sh
      - run: npm run lint

      # Update the cache with the latest installed dependencies to speed up future installs
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths: node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "shared/package-lock.json" }}
          paths: shared/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "incoming-message-handler/package-lock.json" }}
          paths: incoming-message-handler/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "audit-log-api/package-lock.json" }}
          paths: audit-log-api/node_modules

      - save_cache:
          key: v1-npm-deps-{{ checksum "audit-log-portal/package-lock.json" }}
          paths: audit-log-portal/node_modules

  test:
    docker:
      - image: cimg/node:15.9.0
    working_directory: ~
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "shared/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "incoming-message-handler/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "audit-log-api/package-lock.json" }}

      - restore_cache:
          key: v1-npm-deps-{{ checksum "audit-log-portal/package-lock.json" }}

      - run: ./scripts/install-all.sh
      - run: ./scripts/test-all.sh
      - store_test_results:
          path: ./shared/test-results/jest/
      - store_test_results:
          path: ./incoming-message-handler/test-results/jest/
      - store_test_results:
          path: ./audit-log-api/test-results/jest/
      - store_test_results:
          path: ./audit-log-portal/test-results/jest/

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
