version: "3.2"
services:
  ibmmq:
    image: ibmcom/mq
    container_name: ibmmq
    ports:
      - 1414:1414
      - 9157:9157
      - 9443:9443
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=BR7_QM
  localstack:
    image: localstack/localstack:latest
    container_name: aws-learning
    ports:
      - "4563-4599:4563-4599"
      - "8055:8080"
    environment:
      - SERVICES=sqs,lambda,s3
      - DEBUG=1
      - LAMBDA_REMOTE_DOCKER=false
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
