name: Lint and Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    name: Lint and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4

      - name: Setup node version
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version-file: .nvmrc
          
      - name: ⛓️ SLSA Supply Chain Security
        uses: ministryofjustice/devsecops-actions/sca/slsa@805c9da24fe7083e24b8435a626463b25951d278 # v1.4.0

      - name: Install NPM packages
        run: npm ci --ignore-scripts

      - name: Run check
        run: npm run check
        
      - name: Run linting
        run: npm run lint

      - name: Run build
        run: npm run build
