name: Update npm dependencies

on:
  schedule:
    - cron: '0 9 * * 1-5'

jobs:
  update_deps:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.3.1

      - name: Install dependencies
        run: make install

      - name: Update dependencies
        run: npm run update-deps

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: 'auto/update-npm-deps'
          commit-message: 'Update npm dependencies'
          delete-branch: true
          title: 'Update npm dependencies'

      - name: Check PR information
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number}}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"
