name: Update npm dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

jobs:
  update_deps:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4

      - name: Setup node version
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 20.18.0
          
      - name: ⛓️ SLSA Supply Chain Security
        uses: ministryofjustice/devsecops-actions/sca/slsa@559ec2408860d9237cc472a5710e61c1c2187ffa # v1.4.0

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Update dependencies
        run: npm run update-deps

# Disabled temporarily while we explore alternatives
#      - name: Report Status
#        if: always()
#        uses: ravsamhq/notify-slack-action@4ed28566c2bdcdaee6dca2b46b9666d01b4ed8a4 # v1
#        with:
#          status: ${{ job.status }}
#          notification_title: "GitHub action failed"
#          message_format: ":elmo-fire: *{workflow}* {status_message} in <{repo_url}|{repo}>"
#          notify_when: "failure"
#          footer: "Linked to Repo <{repo_url}|{repo}>"
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50 # v6
        with:
          branch: auto/update-npm-deps
          delete-branch: true
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          commit-message: Update npm dependencies
          title: Update npm dependencies
          body: >
            Automated npm dependency updates generated by the
            [Update npm dependencies](https://github.com/ministryofjustice/bichard7-next-audit-logging/actions/workflows/update-npm-deps.yml)
            workflow.

      - name: Check PR information
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number}}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"
