name: Update npm dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

jobs:
  update_deps:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4

      - name: Setup node version
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version-file: '.nvmrc'
          
      - name: Print node version
        run: node -v
          
      - name: ⛓️ SLSA Supply Chain Security
        uses: ministryofjustice/devsecops-actions/sca/slsa@8c77d3a65a46d1d4b5416eafae5b84371ecd797d # v1.5.0

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Update dependencies
        run: npm run update-deps

      - name: Report Status
        if: failure()
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d #v2.0.0  
        with:
          webhook-type: incoming-webhook
          payload: |
            text: "GitHub action failed"  
            attachments:  
              - color: "#a30000" # Red  
                blocks:  
                  - type: "section"  
                    text:  
                      type: "mrkdwn"  
                      text: ":elmo-fire: *${{ github.workflow }}* failed in <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"  
                  - type: "context"  
                    elements:  
                      - type: "mrkdwn"  
                        text: "Linked to Repo <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"  
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50 # v6
        with:
          branch: auto/update-npm-deps
          delete-branch: true
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          commit-message: Update npm dependencies
          title: Update npm dependencies
          body: >
            Automated npm dependency updates generated by the
            [Update npm dependencies](https://github.com/ministryofjustice/bichard7-next-audit-logging/actions/workflows/update-npm-deps.yml)
            workflow.

      - name: Check PR information
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number}}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"
